--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dim9999/RankNotes
build-by-default: true
branches:
- master
projects:
  RankNotes:
    path: ""
    lint:
      phpstan: false 
    icon: icon.png
...
